database:
  url:      jdbc:mysql://localhost:3306/minepath  # or your SQL Server/Postgres URL
  user:     root
  password: Qwerty@061205
prices:
  # NFT Lootbox prices
  basic_nft: 500
  premium_nft: 1500
  ultimate_nft: 3000

# NFT Lootbox configuration
nft_lootbox:
  # Path to the NFT-Plugin directory
  plugin_path: "D:/Code/NFT-Plugin/LootBox/NFT-Plugin"

  # Tier drop rates for each lootbox type
  basic:
    common: 80
    rare: 15
    epic: 4
    legendary: 0.9
    mythic: 0.1

  premium:
    common: 50
    rare: 35
    epic: 10
    legendary: 4
    mythic: 1

  ultimate:
    common: 30
    rare: 40
    epic: 20
    legendary: 8
    mythic: 2

  # NFT types and their drop rates within each tier
  tiers:
    common:
      lucky_charm_1: 60
      explosion_pickaxe_1: 20
      laser_pickaxe_1: 20

    rare:
      lucky_charm_2: 40
      explosion_pickaxe_2: 30
      laser_pickaxe_2: 30

    epic:
      lucky_charm_5: 40
      explosion_pickaxe_3: 30
      laser_pickaxe_3: 30

    legendary:
      lucky_charm_10: 40
      explosion_pickaxe_4: 30
      laser_pickaxe_4: 30

    mythic:
      lucky_charm_20: 40
      explosion_pickaxe_5: 30
      laser_pickaxe_5: 30
