name: LootBoxPlugin
main: com.example.lootbox.LootBoxPlugin
version: 1.0
api-version: 1.18
depend: [Vault]  

commands:
  lootbox:
    description: Purchase lootboxes
    usage: /lootbox <type> <amount>
