name: LootBoxPlugin
main: com.example.lootbox.LootBoxPlugin
version: "1.0"
api-version: "1.18"
depend: [Vault, NFTPlugin]

commands:
  nftlootbox:
    description: Purchase NFT lootboxes
    usage: /nftlootbox <type> <amount>
    aliases: [nftbox]
